try {
  hello();
} catch (error) {
  console.log(error);
}

try {
    otraFuncion();
}catch{
    console.log('esto es un error');
}

 

